backend:
  name: git-gateway
  branch: master
  # name: test-repo
media_folder: public/img
public_folder: img
collections:
  - label: "Blog Posts"
    name: "posts"
    folder: "public/data/posts"
    create: true
    identifier_field: "title"
    slug: "{{fields.slug}}"
    format: "json"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string",pattern: ['^[a-zA-Z0-9-_]+$', "Alphanumeric with dashes or underscores"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "coverImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}